version: 2.1

jobs:
  build:
    docker:
      - image: nimlang/nim:1.6.6-alpine-slim
    resource_class: medium
    steps:
      - checkout
      - run:
          name: compile Nim
          command: |
            # ls src/**/*.nim | xargs -n 1 nim c
            nim c src/temperature.nim
            nim c src/fibonacci.nim
            nim c src/greeting.nim
      - run:
          name: run tests
          command: |
            testament pattern "tests/*.nim"
